### ISSUE TITLE
Loading locally?

### ISSUE THREAD

**Issue by klosteinmann** [SebastianAigner/twemoji-amazing#13]
Hi I'd like to use twemoji-amazing,

from within the CSS I can see it loads it directly via the official Twemoji CDN.
Is it „legally” possible to use Twemoji locally within your projects to avoid GDPR issues and of course to have a fallback?
You could theroetically allow it to load from within multiple urls.

This might also reduce sequential loadtimes alltogether by utilizing caching. Even though 8 MB is pretty big download so you would have to chain it appropiately and not overuse icons on your project. Reason I'm mnetioning this I'm planing on using it on a e-Commerce website.

Great project

Best wishes
Klosteinmann

**Comment by SebastianAigner** [comment]
Hi Klosteinmann!

Yes, you can download self-host Twemoji Assets as per [the official Twemoji repository](https://github.com/twitter/twemoji#download) as long as you follow their [attribution requirements](https://github.com/twitter/twemoji#attribution-requirements).

I don't have "official" support for self-hosted images in `twemoji-amazing`, but seeing how it's just a static CSS file that you can [download](https://github.com/SebastianAigner/twemoji-amazing/releases/tag/v1.0.0) and modify, you can simply Find-And-Replace the `https://twemoji.maxcdn.com/v/latest/svg/` prefixes and replace it with your servers address (or relative path).

Hope that answers it!

**Comment by SebastianAigner** [comment]
Going to close this issue as resolve for now. If you have further questions, feel free to open a new issue! 🎉
