### ISSUE TITLE
Missing svgs

### ISSUE THREAD

**Issue by eivholt** [SebastianAigner/twemoji-amazing#14]
At some point in early january many of the emojis stopped being delivered. Example of missing svg:
https://cdn.jsdelivr.net/npm/twemoji@11.3.0/2/svg/1fab4.svg
https://cdn.jsdelivr.net/npm/twemoji@11.3.0/2/svg/1faa5.svg
https://cdn.jsdelivr.net/npm/twemoji@11.3.0/2/svg/1f9c6.svg
https://cdn.jsdelivr.net/npm/twemoji@11.3.0/2/svg/1faa2.svg
https://cdn.jsdelivr.net/npm/twemoji@11.3.0/2/svg/1fac0.svg

I have referenced the css with the following url: https://cdn.jsdelivr.net/gh/SebastianAigner/twemoji-amazing@1.1.0/twemoji-amazing.css

**Comment by chr15m** [comment]
@SebastianAigner I think you can fix this by using twitter/twemoji's GitHub as the source for the svg files via jsdeliver like this:

https://cdn.jsdelivr.net/gh/twitter/twemoji@master/assets/svg/CODE.svg

For example this one is missing:

https://cdn.jsdelivr.net/npm/twemoji@11.3.0/2/svg/1fa99.svg

But it can be found here:

https://cdn.jsdelivr.net/gh/twitter/twemoji@master/assets/svg/1fa99.svg

**Comment by SebastianAigner** [comment]
Fixed in https://github.com/SebastianAigner/twemoji-amazing/releases/tag/v1.2.0 – I've also patched version 1.1 to point to the new CDN, since there's no point in keeping around broken links in CSS. Thanks for the report! 🎉

**Comment by chr15m** [comment]
Thanks, will test!

**Comment by SebastianAigner** [comment]
Just for versioning purposes, I’ve elected to unpublish 1.2, since it’s really just a fix for 1.1, so anybody depending on 1.1 will undoubtedly want the new version — just so that we’re not getting into multiple releases with the same contents if this situation should repeat in the future 😄 tldr; just use 1.1 for the fix!
