### ISSUE TITLE
List of 341 emojis that are in Twemoji but are not in this project including Regional Indicator Symbols

### ISSUE THREAD

**Issue by AceLewis** [SebastianAigner/twemoji-amazing#3]
This project does not support [Regional Indicator Symbols](https://en.wikipedia.org/wiki/Regional_Indicator_Symbol). I need to use these on my webpage so I can't use this project and am stuck with [twemoji-awesome](https://github.com/ellekasai/twemoji-awesome/) for the time being. I also thought what other emojis are missing and have appended them to this issue.

Regional Indicator Symbols symbols are supported by [twemoji-awesome](https://github.com/ellekasai/twemoji-awesome/). In twemoji-awesome these are called either XX or squared-X (where X is the RIS), however I belive the name should be as specified by the Unicode Consortium so regional-indicator-symbol-letter-X http://www.unicode.org/charts/PDF/U1F100.pdf. These symbols are used on Twitter as emojis and are on the CDN used by this project e.g. https://twemoji.maxcdn.com/v/latest/svg/1f1e6.svg

I have put their hex codes for all of the missing emojis here they can be checked off when added. They are mostly emoji zwj sequences and new emojis.  https://www.unicode.org/Public/emoji/13.0/emoji-test.txt https://www.unicode.org/Public/emoji/13.0/emoji-zwj-sequences.txt

- [ ] 1f1e6
- [ ] 1f1e7
- [ ] 1f1e8
- [ ] 1f1e9
- [ ] 1f1ea
- [ ] 1f1eb
- [ ] 1f1ec
- [ ] 1f1ed
- [ ] 1f1ee
- [ ] 1f1ef
- [ ] 1f1f0
- [ ] 1f1f1
- [ ] 1f1f2
- [ ] 1f1f3
- [ ] 1f1f4
- [ ] 1f1f5
- [ ] 1f1f6
- [ ] 1f1f7
- [ ] 1f1f8
- [ ] 1f1f9
- [ ] 1f1fa
- [ ] 1f1fb
- [ ] 1f1fc
- [ ] 1f1fd
- [ ] 1f1fe
- [ ] 1f1ff
- [ ] 1f3f3-fe0f-200d-26a7-fe0f
- [ ] 1f408-200d-2b1b
- [ ] 1f43b-200d-2744-fe0f
- [ ] 1f468-1f3fb-200d-1f37c
- [ ] 1f468-1f3fb-200d-1f384
- [ ] 1f468-1f3fb-200d-1f91d-200d-1f468-1f3fc
- [ ] 1f468-1f3fb-200d-1f91d-200d-1f468-1f3fd
- [ ] 1f468-1f3fb-200d-1f91d-200d-1f468-1f3fe
- [ ] 1f468-1f3fb-200d-1f91d-200d-1f468-1f3ff
- [ ] 1f468-1f3fc-200d-1f37c
- [ ] 1f468-1f3fc-200d-1f384
- [ ] 1f468-1f3fc-200d-1f91d-200d-1f468-1f3fd
- [ ] 1f468-1f3fc-200d-1f91d-200d-1f468-1f3fe
- [ ] 1f468-1f3fc-200d-1f91d-200d-1f468-1f3ff
- [ ] 1f468-1f3fd-200d-1f37c
- [ ] 1f468-1f3fd-200d-1f384
- [ ] 1f468-1f3fd-200d-1f91d-200d-1f468-1f3fe
- [ ] 1f468-1f3fd-200d-1f91d-200d-1f468-1f3ff
- [ ] 1f468-1f3fe-200d-1f37c
- [ ] 1f468-1f3fe-200d-1f384
- [ ] 1f468-1f3fe-200d-1f91d-200d-1f468-1f3ff
- [ ] 1f468-1f3ff-200d-1f37c
- [ ] 1f468-1f3ff-200d-1f384
- [ ] 1f468-200d-1f37c
- [ ] 1f468-200d-1f384
- [ ] 1f469-1f3fb-200d-1f37c
- [ ] 1f469-1f3fb-200d-1f384
- [ ] 1f469-1f3fb-200d-1f91d-200d-1f469-1f3fc
- [ ] 1f469-1f3fb-200d-1f91d-200d-1f469-1f3fd
- [ ] 1f469-1f3fb-200d-1f91d-200d-1f469-1f3fe
- [ ] 1f469-1f3fb-200d-1f91d-200d-1f469-1f3ff
- [ ] 1f469-1f3fc-200d-1f37c
- [ ] 1f469-1f3fc-200d-1f384
- [ ] 1f469-1f3fc-200d-1f91d-200d-1f469-1f3fd
- [ ] 1f469-1f3fc-200d-1f91d-200d-1f469-1f3fe
- [ ] 1f469-1f3fc-200d-1f91d-200d-1f469-1f3ff
- [ ] 1f469-1f3fd-200d-1f37c
- [ ] 1f469-1f3fd-200d-1f384
- [ ] 1f469-1f3fd-200d-1f91d-200d-1f469-1f3fe
- [ ] 1f469-1f3fd-200d-1f91d-200d-1f469-1f3ff
- [ ] 1f469-1f3fe-200d-1f37c
- [ ] 1f469-1f3fe-200d-1f384
- [ ] 1f469-1f3fe-200d-1f91d-200d-1f469-1f3ff
- [ ] 1f469-1f3ff-200d-1f37c
- [ ] 1f469-1f3ff-200d-1f384
- [ ] 1f469-200d-1f37c
- [ ] 1f469-200d-1f384
- [ ] 1f470-1f3fb-200d-2640-fe0f
- [ ] 1f470-1f3fb-200d-2642-fe0f
- [ ] 1f470-1f3fc-200d-2640-fe0f
- [ ] 1f470-1f3fc-200d-2642-fe0f
- [ ] 1f470-1f3fd-200d-2640-fe0f
- [ ] 1f470-1f3fd-200d-2642-fe0f
- [ ] 1f470-1f3fe-200d-2640-fe0f
- [ ] 1f470-1f3fe-200d-2642-fe0f
- [ ] 1f470-1f3ff-200d-2640-fe0f
- [ ] 1f470-1f3ff-200d-2642-fe0f
- [ ] 1f470-200d-2640-fe0f
- [ ] 1f470-200d-2642-fe0f
- [ ] 1f574-1f3fb-200d-2640-fe0f
- [ ] 1f574-1f3fb-200d-2642-fe0f
- [ ] 1f574-1f3fc-200d-2640-fe0f
- [ ] 1f574-1f3fc-200d-2642-fe0f
- [ ] 1f574-1f3fd-200d-2640-fe0f
- [ ] 1f574-1f3fd-200d-2642-fe0f
- [ ] 1f574-1f3fe-200d-2640-fe0f
- [ ] 1f574-1f3fe-200d-2642-fe0f
- [ ] 1f574-1f3ff-200d-2640-fe0f
- [ ] 1f574-1f3ff-200d-2642-fe0f
- [ ] 1f574-fe0f-200d-2640-fe0f
- [ ] 1f574-fe0f-200d-2642-fe0f
- [ ] 1f6d6
- [ ] 1f6d7
- [ ] 1f6fb
- [ ] 1f6fc
- [ ] 1f90c-1f3fb
- [ ] 1f90c-1f3fc
- [ ] 1f90c-1f3fd
- [ ] 1f90c-1f3fe
- [ ] 1f90c-1f3ff
- [ ] 1f90c
- [ ] 1f935-1f3fb-200d-2640-fe0f
- [ ] 1f935-1f3fb-200d-2642-fe0f
- [ ] 1f935-1f3fc-200d-2640-fe0f
- [ ] 1f935-1f3fc-200d-2642-fe0f
- [ ] 1f935-1f3fd-200d-2640-fe0f
- [ ] 1f935-1f3fd-200d-2642-fe0f
- [ ] 1f935-1f3fe-200d-2640-fe0f
- [ ] 1f935-1f3fe-200d-2642-fe0f
- [ ] 1f935-1f3ff-200d-2640-fe0f
- [ ] 1f935-1f3ff-200d-2642-fe0f
- [ ] 1f935-200d-2640-fe0f
- [ ] 1f935-200d-2642-fe0f
- [ ] 1f972
- [ ] 1f977-1f3fb
- [ ] 1f977-1f3fc
- [ ] 1f977-1f3fd
- [ ] 1f977-1f3fe
- [ ] 1f977-1f3ff
- [ ] 1f977
- [ ] 1f978
- [ ] 1f9a3
- [ ] 1f9a4
- [ ] 1f9ab
- [ ] 1f9ac
- [ ] 1f9ad
- [ ] 1f9cb
- [ ] 1f9d1-1f3fb-200d-1f33e
- [ ] 1f9d1-1f3fb-200d-1f373
- [ ] 1f9d1-1f3fb-200d-1f37c
- [ ] 1f9d1-1f3fb-200d-1f384
- [ ] 1f9d1-1f3fb-200d-1f393
- [ ] 1f9d1-1f3fb-200d-1f3a4
- [ ] 1f9d1-1f3fb-200d-1f3a8
- [ ] 1f9d1-1f3fb-200d-1f3eb
- [ ] 1f9d1-1f3fb-200d-1f3ed
- [ ] 1f9d1-1f3fb-200d-1f4bb
- [ ] 1f9d1-1f3fb-200d-1f4bc
- [ ] 1f9d1-1f3fb-200d-1f527
- [ ] 1f9d1-1f3fb-200d-1f52c
- [ ] 1f9d1-1f3fb-200d-1f680
- [ ] 1f9d1-1f3fb-200d-1f692
- [ ] 1f9d1-1f3fb-200d-1f91d-200d-1f9d1-1f3fc
- [ ] 1f9d1-1f3fb-200d-1f91d-200d-1f9d1-1f3fd
- [ ] 1f9d1-1f3fb-200d-1f91d-200d-1f9d1-1f3fe
- [ ] 1f9d1-1f3fb-200d-1f91d-200d-1f9d1-1f3ff
- [ ] 1f9d1-1f3fb-200d-1f9af
- [ ] 1f9d1-1f3fb-200d-1f9b0
- [ ] 1f9d1-1f3fb-200d-1f9b1
- [ ] 1f9d1-1f3fb-200d-1f9b2
- [ ] 1f9d1-1f3fb-200d-1f9b3
- [ ] 1f9d1-1f3fb-200d-1f9bc
- [ ] 1f9d1-1f3fb-200d-1f9bd
- [ ] 1f9d1-1f3fb-200d-2695-fe0f
- [ ] 1f9d1-1f3fb-200d-2696-fe0f
- [ ] 1f9d1-1f3fb-200d-2708-fe0f
- [ ] 1f9d1-1f3fc-200d-1f33e
- [ ] 1f9d1-1f3fc-200d-1f373
- [ ] 1f9d1-1f3fc-200d-1f37c
- [ ] 1f9d1-1f3fc-200d-1f384
- [ ] 1f9d1-1f3fc-200d-1f393
- [ ] 1f9d1-1f3fc-200d-1f3a4
- [ ] 1f9d1-1f3fc-200d-1f3a8
- [ ] 1f9d1-1f3fc-200d-1f3eb
- [ ] 1f9d1-1f3fc-200d-1f3ed
- [ ] 1f9d1-1f3fc-200d-1f4bb
- [ ] 1f9d1-1f3fc-200d-1f4bc
- [ ] 1f9d1-1f3fc-200d-1f527
- [ ] 1f9d1-1f3fc-200d-1f52c
- [ ] 1f9d1-1f3fc-200d-1f680
- [ ] 1f9d1-1f3fc-200d-1f692
- [ ] 1f9d1-1f3fc-200d-1f91d-200d-1f9d1-1f3fd
- [ ] 1f9d1-1f3fc-200d-1f91d-200d-1f9d1-1f3fe
- [ ] 1f9d1-1f3fc-200d-1f91d-200d-1f9d1-1f3ff
- [ ] 1f9d1-1f3fc-200d-1f9af
- [ ] 1f9d1-1f3fc-200d-1f9b0
- [ ] 1f9d1-1f3fc-200d-1f9b1
- [ ] 1f9d1-1f3fc-200d-1f9b2
- [ ] 1f9d1-1f3fc-200d-1f9b3
- [ ] 1f9d1-1f3fc-200d-1f9bc
- [ ] 1f9d1-1f3fc-200d-1f9bd
- [ ] 1f9d1-1f3fc-200d-2695-fe0f
- [ ] 1f9d1-1f3fc-200d-2696-fe0f
- [ ] 1f9d1-1f3fc-200d-2708-fe0f
- [ ] 1f9d1-1f3fd-200d-1f33e
- [ ] 1f9d1-1f3fd-200d-1f373
- [ ] 1f9d1-1f3fd-200d-1f37c
- [ ] 1f9d1-1f3fd-200d-1f384
- [ ] 1f9d1-1f3fd-200d-1f393
- [ ] 1f9d1-1f3fd-200d-1f3a4
- [ ] 1f9d1-1f3fd-200d-1f3a8
- [ ] 1f9d1-1f3fd-200d-1f3eb
- [ ] 1f9d1-1f3fd-200d-1f3ed
- [ ] 1f9d1-1f3fd-200d-1f4bb
- [ ] 1f9d1-1f3fd-200d-1f4bc
- [ ] 1f9d1-1f3fd-200d-1f527
- [ ] 1f9d1-1f3fd-200d-1f52c
- [ ] 1f9d1-1f3fd-200d-1f680
- [ ] 1f9d1-1f3fd-200d-1f692
- [ ] 1f9d1-1f3fd-200d-1f91d-200d-1f9d1-1f3fe
- [ ] 1f9d1-1f3fd-200d-1f91d-200d-1f9d1-1f3ff
- [ ] 1f9d1-1f3fd-200d-1f9af
- [ ] 1f9d1-1f3fd-200d-1f9b0
- [ ] 1f9d1-1f3fd-200d-1f9b1
- [ ] 1f9d1-1f3fd-200d-1f9b2
- [ ] 1f9d1-1f3fd-200d-1f9b3
- [ ] 1f9d1-1f3fd-200d-1f9bc
- [ ] 1f9d1-1f3fd-200d-1f9bd
- [ ] 1f9d1-1f3fd-200d-2695-fe0f
- [ ] 1f9d1-1f3fd-200d-2696-fe0f
- [ ] 1f9d1-1f3fd-200d-2708-fe0f
- [ ] 1f9d1-1f3fe-200d-1f33e
- [ ] 1f9d1-1f3fe-200d-1f373
- [ ] 1f9d1-1f3fe-200d-1f37c
- [ ] 1f9d1-1f3fe-200d-1f384
- [ ] 1f9d1-1f3fe-200d-1f393
- [ ] 1f9d1-1f3fe-200d-1f3a4
- [ ] 1f9d1-1f3fe-200d-1f3a8
- [ ] 1f9d1-1f3fe-200d-1f3eb
- [ ] 1f9d1-1f3fe-200d-1f3ed
- [ ] 1f9d1-1f3fe-200d-1f4bb
- [ ] 1f9d1-1f3fe-200d-1f4bc
- [ ] 1f9d1-1f3fe-200d-1f527
- [ ] 1f9d1-1f3fe-200d-1f52c
- [ ] 1f9d1-1f3fe-200d-1f680
- [ ] 1f9d1-1f3fe-200d-1f692
- [ ] 1f9d1-1f3fe-200d-1f91d-200d-1f9d1-1f3ff
- [ ] 1f9d1-1f3fe-200d-1f9af
- [ ] 1f9d1-1f3fe-200d-1f9b0
- [ ] 1f9d1-1f3fe-200d-1f9b1
- [ ] 1f9d1-1f3fe-200d-1f9b2
- [ ] 1f9d1-1f3fe-200d-1f9b3
- [ ] 1f9d1-1f3fe-200d-1f9bc
- [ ] 1f9d1-1f3fe-200d-1f9bd
- [ ] 1f9d1-1f3fe-200d-2695-fe0f
- [ ] 1f9d1-1f3fe-200d-2696-fe0f
- [ ] 1f9d1-1f3fe-200d-2708-fe0f
- [ ] 1f9d1-1f3ff-200d-1f33e
- [ ] 1f9d1-1f3ff-200d-1f373
- [ ] 1f9d1-1f3ff-200d-1f37c
- [ ] 1f9d1-1f3ff-200d-1f384
- [ ] 1f9d1-1f3ff-200d-1f393
- [ ] 1f9d1-1f3ff-200d-1f3a4
- [ ] 1f9d1-1f3ff-200d-1f3a8
- [ ] 1f9d1-1f3ff-200d-1f3eb
- [ ] 1f9d1-1f3ff-200d-1f3ed
- [ ] 1f9d1-1f3ff-200d-1f4bb
- [ ] 1f9d1-1f3ff-200d-1f4bc
- [ ] 1f9d1-1f3ff-200d-1f527
- [ ] 1f9d1-1f3ff-200d-1f52c
- [ ] 1f9d1-1f3ff-200d-1f680
- [ ] 1f9d1-1f3ff-200d-1f692
- [ ] 1f9d1-1f3ff-200d-1f9af
- [ ] 1f9d1-1f3ff-200d-1f9b0
- [ ] 1f9d1-1f3ff-200d-1f9b1
- [ ] 1f9d1-1f3ff-200d-1f9b2
- [ ] 1f9d1-1f3ff-200d-1f9b3
- [ ] 1f9d1-1f3ff-200d-1f9bc
- [ ] 1f9d1-1f3ff-200d-1f9bd
- [ ] 1f9d1-1f3ff-200d-2695-fe0f
- [ ] 1f9d1-1f3ff-200d-2696-fe0f
- [ ] 1f9d1-1f3ff-200d-2708-fe0f
- [ ] 1f9d1-200d-1f33e
- [ ] 1f9d1-200d-1f373
- [ ] 1f9d1-200d-1f37c
- [ ] 1f9d1-200d-1f384
- [ ] 1f9d1-200d-1f393
- [ ] 1f9d1-200d-1f3a4
- [ ] 1f9d1-200d-1f3a8
- [ ] 1f9d1-200d-1f3eb
- [ ] 1f9d1-200d-1f3ed
- [ ] 1f9d1-200d-1f4bb
- [ ] 1f9d1-200d-1f4bc
- [ ] 1f9d1-200d-1f527
- [ ] 1f9d1-200d-1f52c
- [ ] 1f9d1-200d-1f680
- [ ] 1f9d1-200d-1f692
- [ ] 1f9d1-200d-1f9af
- [ ] 1f9d1-200d-1f9b0
- [ ] 1f9d1-200d-1f9b1
- [ ] 1f9d1-200d-1f9b2
- [ ] 1f9d1-200d-1f9b3
- [ ] 1f9d1-200d-1f9bc
- [ ] 1f9d1-200d-1f9bd
- [ ] 1f9d1-200d-2695-fe0f
- [ ] 1f9d1-200d-2696-fe0f
- [ ] 1f9d1-200d-2708-fe0f
- [ ] 1fa74
- [ ] 1fa83
- [ ] 1fa84
- [ ] 1fa85
- [ ] 1fa86
- [ ] 1fa96
- [ ] 1fa97
- [ ] 1fa98
- [ ] 1fa99
- [ ] 1fa9a
- [ ] 1fa9b
- [ ] 1fa9c
- [ ] 1fa9d
- [ ] 1fa9e
- [ ] 1fa9f
- [ ] 1faa0
- [ ] 1faa1
- [ ] 1faa2
- [ ] 1faa3
- [ ] 1faa4
- [ ] 1faa5
- [ ] 1faa6
- [ ] 1faa7
- [ ] 1faa8
- [ ] 1fab0
- [ ] 1fab1
- [ ] 1fab2
- [ ] 1fab3
- [ ] 1fab4
- [ ] 1fab5
- [ ] 1fab6
- [ ] 1fac0
- [ ] 1fac1
- [ ] 1fac2
- [ ] 1fad0
- [ ] 1fad1
- [ ] 1fad2
- [ ] 1fad3
- [ ] 1fad4
- [ ] 1fad5
- [ ] 1fad6
- [ ] 26a7
- [ ] 26f7-1f3fb
- [ ] 26f7-1f3fc
- [ ] 26f7-1f3fd
- [ ] 26f7-1f3fe
- [ ] 26f7-1f3ff
- [ ] e50a

**Comment by SebastianAigner** [comment]
Hi @AceLewis !

✨ I've just pushed a brand-new version of twemoji-amazing that has reworked the resolution algorithm.

twemoji-amazing now generates CSS classes for regional indicators and all the fancy ZWJ combinations that Twemoji has to offer (some of which don't have an officially specified name, or at least none that I could find. I am using a fallback strategy for those), including the ominous Shibuya emoji.

I'm happy to say that this means twemoji-amazing now supports 3360/3360 available Twemojis. 🥳

Have fun integrating it on your site! 🌐
