### ISSUE TITLE
Icon Font

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [SebastianAigner/twemoji-amazing#5]
Any chance we could have an icon font just like with Font Awesome? That way we could also use Twemoji [with pseudo elements](https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements).

Thank you very much in advance!

**Comment by SebastianAigner** [comment]
Hi @rodrigoalcarazdelaosa and thanks for the request. Do you have a particular use case that prevents you from using twemoji-amazing as-is?

I honestly think it's unlikely an icon font will be supported in the context of twemoji-amazing, since generating webfonts seems disproportionally difficult in comparison to the possible use. Maybe the folks at https://github.com/eosrei/twemoji-color-font can help?

**Comment by rodrigoalcarazdelaosa** [comment]
> Hi @rodrigoalcarazdelaosa and thanks for the request. Do you have a particular use case that prevents you from using twemoji-amazing as-is?

I'm using [Wowchemy](https://wowchemy.com) to build [my site](https://rodrigoalcarazdelaosa.me/en/). Wowchemy has what it calls [**callouts**](https://wowchemy.com/docs/content/writing-markdown-latex/#callouts), which are [Hugo shortcodes](https://gohugo.io/content-management/shortcodes/) (source [here](https://github.com/wowchemy/wowchemy-hugo-modules/blob/master/wowchemy/layouts/shortcodes/callout.html)). The associated CSS can be found [here](https://github.com/wowchemy/wowchemy-hugo-modules/blob/master/wowchemy/assets/scss/wowchemy/_callouts.scss), and, as you can see, the Font Awesome `font-family` is used for the corresponding icons. I wanted to substitute some of those icons with emojis, and was having trouble getting Twemoji to work with them. At the I was able to do it using [`hugo-mod-twemoji`](https://github.com/jakejarvis/hugo-mod-twemoji) by directly loading the `svgs` (example [here](https://github.com/rodrigoalcarazdelaosa/fisiquimicamente-con-rodri/blob/5e21a20b85e464f3a5275db2454faf95f89b505c/assets/scss/custom.scss#L332)).

**Comment by SebastianAigner** [comment]
I hope you managed to figure things out with your Hugo page! For now, I'm going to close this as out-of-scope for this project specifically. But I still think about your idea every now and then, so who knows what might happen when I at some point happen to have some extra free time and energy 😁
