### ISSUE TITLE
Linking stylesheet and Country Flags

### ISSUE THREAD

**Issue by jamietyger** [SebastianAigner/twemoji-amazing#6]
Hi there,

I've tried linking the stylesheet 
`<link rel="stylesheet" href="https://raw.githubusercontent.com/SebastianAigner/twemoji-amazing/master/twemoji-amazing.css"/>`  in my html head but I can't seem to get the emoji's to display?

Also is there any guidance on use for country flags?

Thanks in advance

**Comment by Driaan** [comment]
@jamietyger raw.githubusercontent.com serving issue, see devtools console on chrome eg.

> Refused to apply style from 'https://raw.githubusercontent.com/SebastianAigner/twemoji-amazing/master/twemoji-amazing.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

So just download the file & include it locally or host it elsewhere.

As for flags, use any standard emoji flag eg.

South Africa:

```twa-flag-south-africa```

Also see https://emojipedia.org/flags/

**Comment by SebastianAigner** [comment]
@jamietyger twemoji-amazing now also has releases, meaning you can use a CDN like jsDelivr to use the CSS file:

https://cdn.jsdelivr.net/gh/SebastianAigner/twemoji-amazing@1.0.0/twemoji-amazing.css

Hope that helps! Do let me know if there's any more questions. Happy holidays 🎄
