### ISSUE TITLE
Add releases

### ISSUE THREAD

**Issue by lucaceriani** [SebastianAigner/twemoji-amazing#8]
I would like to suggest to add releases with tags so that when using jsDelivr we can point to a specific version and not to the master branch. Thanks!

**Comment by SebastianAigner** [comment]
Hi @lucaceriani! I've just published twemoji-amazing 1.0.0 as a release.

You can now use it from jsDelivr with the verison tag "1.0.0"!
https://cdn.jsdelivr.net/gh/SebastianAigner/twemoji-amazing@1.0.0/twemoji-amazing.css

Hope this works for you – cheers and happy holidays! 🎄

**Comment by lucaceriani** [comment]
Thank you! This repo was awesome and you made it better.
Happy holidays!
